# Spring Boot uygulamasının adını belirliyoruz.
# Bu isim loglarda ve Spring araçlarında uygulamayı tanımak için kullanılır.
spring.application.name=miniwallet

# Docker içerisinde çalışan MySQL veritabanına bağlanacağımız adresi belirliyoruz.
# Windows'taki 3307 portu, container içerisindeki 3306 portuna yönlendirilmiştir.
spring.datasource.url=jdbc:mysql://localhost:3307/miniwallet_db

# Veritabanı bilgilerini doğrudan bu dosyaya yazmıyoruz.
# Değerler IntelliJ Run Configuration içindeki environment variable'lardan alınır.
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Entity sınıflarına göre veritabanı tablolarını oluşturur ve günceller.
# Öğrenme aşamasında update kullanacağız; ileride Flyway kullanabiliriz.
spring.jpa.hibernate.ddl-auto=update

# Hibernate'in oluşturduğu SQL sorgularını konsolda görmemizi sağlar.
spring.jpa.show-sql=true

# Konsoldaki SQL sorgularını daha okunabilir şekilde biçimlendirir.
spring.jpa.properties.hibernate.format_sql=true

# Controller veya JSON oluşturma aşamasında farkında olmadan sorgu çalışmasını engeller.
# Veritabanı işlemlerini Service katmanında kontrollü şekilde gerçekleştireceğiz.
spring.jpa.open-in-view=false